name: Analise-de-Vendas-CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  CI:
    runs-on: ubuntu-latest #${{ matrix.os }}
    #strategy:
      #matrix:
        #os: ['ubuntu-latest', 'windows-latest']
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.8.0
    
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}
    
    - name: build Docker
      uses: docker/build-push-action@v6.12.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          kir97/analise-vendas
